mybatis-plus:
  type-aliases-package: com.cbc.myblog.domain
  type-handlers-package: com.cbc.myblog.persistence.typeHandler
  mapper-locations: com/cbc/myblog/persistence/*Mapper.xml
spring:
  liquibase:
    change-log: classpath:db/liquibase/master.xml
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cbc_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 674181203
      sql-script-encoding: UTF-8
      hikari:
        maximum-pool-size: 10
        max-lifetime: 1765000
logging:
  level:
    com.cbc.myblog: debug
